name: Wordcloud repo topics
description: Generates a word cloud SVG from your repository topics
author: stefani-gifta

inputs:
  token:
    description: GitHub token
    required: true
  min_font_size:
    description: Smallest font size in pixels
    required: false
    default: '14'
  max_font_size:
    description: Largest font size in pixels
    required: false
    default: '20'
  svg_width:
    description: SVG width in pixels
    required: false
    default: '680'
  svg_height:
    description: SVG height in pixels
    required: false
    default: '400'
  color:
    description: Base color for the words
    required: false
    default: '0075ca'
  output_file:
    description: File name of the resulting SVG
    required: false
    default: 'topics.svg'
  commit_msg:
    description: Commit message when pushing the SVG
    required: false
    default: 'Add repository topics'

runs:
  using: node20
  main: scripts/update-topics.js
  env:
    WORDCLOUD_TOKEN_TOKEN: ${{ inputs.token }}