name: Add topic word cloud

on:
  schedule:
    - cron: '0 0 1 1 *' # runs at 00:00, on day 1 of the month, only in Jan (yearly)  
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate word cloud
        uses: stefani-gifta/wordcloud-repo-topics@main
        with:
          token: ${{ secrets.WORDCLOUD_TOKEN }}
          commit_msg: 'Update word cloud'