name: Add repository topics

on:
  schedule:
    - cron: '0 0 * * *'   # auto run at 00:00 daily
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate word cloud
        uses: stefani-gifta/wordcloud-repo-topics@main
        with:
          token: ${{ secrets.WORDCLOUD_TOKEN }}
          canvas_width: '680'
          canvas_height: '400'
          min_font_size: '14'
          max_font_size: '20'
          color: '0075ca'
          output_file: 'topics.svg'

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add topics.svg
          git diff --staged --quiet || git commit -m "chore: update topic word cloud"
          git push